version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gocyclo
    - misspell
