version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gocyclo
    - dupl
    - misspell

  exclusions:
    generated:
      - 'api/v1alpha1/zz_generated\.deepcopy\.go'
    paths:
      - vendor
      - bin
      - dist
    rules:
      - path: _test\.go
        linters:
          - dupl
          - errcheck
          - gocyclo
      - path: 'api/v1alpha1/zz_generated\.deepcopy\.go'
        linters:
          - goimports
          - gofmt
          - dupl
          - gocyclo

settings:
  errcheck:
    check-type-assertions: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 150
  misspell:
    locale: US
