// k8s-crd/src/scheme.rs
//
// CRD registration helpers for kube-rs.
//
// Usage (in a binary / controller `main.rs`):
//
//   use k8s_crd::scheme;
//   use kube::Client;
//
//   #[tokio::main]
//   async fn main() {
//       let client = Client::try_default().await.unwrap();
//       scheme::install_crds(&client).await.unwrap();
//   }
//
// Or, if you only need the `CustomResourceDefinition` objects to apply
// via kubectl / kustomize:
//
//   let crds = scheme::crd_objects();
//   for crd in &crds {
//       let yaml = serde_yaml::to_string(crd).unwrap();
//       println!("---\n{yaml}");
//   }

use kube::{
    api::{Api, Patch, PatchParams},
    Client, CustomResourceExt,
};
use k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1::CustomResourceDefinition;

use crate::inference_backend::InferenceBackend;
use crate::inference_model::InferenceModel;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Kubernetes API group for all resources in this crate.
pub const GROUP: &str = "inference.eh-ops.io";

/// API version for the v1alpha1 resources.
pub const VERSION: &str = "v1alpha1";

/// Full group/version string.
pub const GROUP_VERSION: &str = "inference.eh-ops.io/v1alpha1";

// ---------------------------------------------------------------------------
// CRD object helpers
// ---------------------------------------------------------------------------

/// Returns the `CustomResourceDefinition` for `InferenceModel`.
///
/// The returned object is suitable for:
///   - Serialising to YAML and applying with `kubectl apply`
///   - Server-side applying via `Api<CustomResourceDefinition>`
pub fn inference_model_crd() -> CustomResourceDefinition {
    InferenceModel::crd()
}

/// Returns the `CustomResourceDefinition` for `InferenceBackend`.
pub fn inference_backend_crd() -> CustomResourceDefinition {
    InferenceBackend::crd()
}

/// Returns all CRD objects managed by this crate in a stable order.
pub fn crd_objects() -> Vec<CustomResourceDefinition> {
    vec![inference_backend_crd(), inference_model_crd()]
}

// ---------------------------------------------------------------------------
// Live cluster installation
// ---------------------------------------------------------------------------

/// Error type for CRD installation failures.
#[derive(Debug, thiserror::Error)]
pub enum SchemeError {
    #[error("kube error: {0}")]
    Kube(#[from] kube::Error),
}

/// Server-side applies all CRDs to the cluster using the provided `Client`.
///
/// This is idempotent: running it on a cluster that already has the CRDs
/// installed will patch them in place (schema upgrades are applied
/// automatically).
///
/// # Errors
/// Returns `SchemeError::Kube` if any API call fails.
pub async fn install_crds(client: &Client) -> Result<(), SchemeError> {
    let api: Api<CustomResourceDefinition> = Api::all(client.clone());
    let ssapply = PatchParams::apply("k8s-crd/scheme.rs").force();

    for crd in crd_objects() {
        let name = crd
            .metadata
            .name
            .as_deref()
            .expect("CRD generated by kube::CustomResourceExt must have a name");

        tracing::info!(%name, "applying CRD");

        api.patch(name, &ssapply, &Patch::Apply(&crd)).await?;
    }

    Ok(())
}

/// Error wrapper for watcher errors that arise during `wait_for_crds`.
#[derive(Debug, thiserror::Error)]
pub enum WaitError {
    #[error("kube error: {0}")]
    Kube(#[from] kube::Error),
    #[error("watcher error waiting for CRD '{crd}': {source}")]
    Watcher {
        crd: String,
        #[source]
        source: kube::runtime::watcher::Error,
    },
}

/// Waits until all CRDs report `Established` in their status conditions.
///
/// Call this after `install_crds` in controller start-up sequences to avoid
/// race conditions where the controller tries to `watch` resources before the
/// API server has registered them.
pub async fn wait_for_crds(client: &Client) -> Result<(), WaitError> {
    use kube::runtime::wait::{await_condition, conditions};

    let api: Api<CustomResourceDefinition> = Api::all(client.clone());

    for crd in crd_objects() {
        let name = crd
            .metadata
            .name
            .as_deref()
            .expect("CRD must have a name")
            .to_owned();

        tracing::info!(name = %name, "waiting for CRD to be established");

        await_condition(api.clone(), &name, conditions::is_crd_established())
            .await
            .map_err(|source| WaitError::Watcher { crd: name.clone(), source })?;
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Serialise CRDs to YAML (useful for code-gen / CI checks)
// ---------------------------------------------------------------------------

/// Returns all CRDs serialised as a multi-document YAML string.
///
/// Suitable for writing to `config/crd/bases/` and applying with
/// `kubectl apply -f`.
///
/// # Errors
/// Returns a `serde_json::Error` if JSON→YAML conversion fails (which should
/// never happen for well-formed CRDs).
pub fn crds_as_yaml() -> Result<String, serde_json::Error> {
    let mut out = String::new();
    for crd in crd_objects() {
        // serde_yaml is not a dependency of this crate; we round-trip through
        // JSON so that callers that need YAML can add serde_yaml themselves.
        // Here we just produce the JSON representation.
        let json = serde_json::to_string_pretty(&crd)?;
        out.push_str("---\n");
        out.push_str(&json);
        out.push('\n');
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn crd_objects_has_two_entries() {
        let crds = crd_objects();
        assert_eq!(crds.len(), 2);
    }

    #[test]
    fn inference_model_crd_name() {
        let crd = inference_model_crd();
        let name = crd.metadata.name.unwrap();
        assert_eq!(name, "inferencemodels.inference.eh-ops.io");
    }

    #[test]
    fn inference_backend_crd_name() {
        let crd = inference_backend_crd();
        let name = crd.metadata.name.unwrap();
        assert_eq!(name, "inferencebackends.inference.eh-ops.io");
    }

    #[test]
    fn crds_serialise_to_json() {
        // Ensures the CRD schemas generated by kube-rs are valid JSON.
        for crd in crd_objects() {
            let json = serde_json::to_string(&crd).unwrap();
            assert!(json.contains("inference.eh-ops.io"));
        }
    }
}
